package bridge

import (
	"net"
	"strconv"
	"strings"
	"testing"
)

// Acceptance test for the proxy_listening probe.
//
// Frozen spec: do not edit this file to fit an implementation. The probe must
// distinguish "something is accepting connections on loopback" from "nothing
// is", and must say where it looked in both cases.

// listenLoopback opens a listener on 127.0.0.1 and returns it with its port.
func listenLoopback(t *testing.T) (net.Listener, int) {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("could not open a loopback listener: %v", err)
	}
	port := ln.Addr().(*net.TCPAddr).Port
	return ln, port
}

func TestProbeProxyListeningPassesWhenSomethingListens(t *testing.T) {
	ln, port := listenLoopback(t)
	defer ln.Close()

	got := ProbeProxyListening(port)

	if got.Name != CheckProxyListening {
		t.Errorf("Name = %q, want %q", got.Name, CheckProxyListening)
	}
	if !got.OK {
		t.Errorf("OK = false for a port that is being listened on (127.0.0.1:%d); err = %v", port, got.Err)
	}
	if got.Err != nil {
		t.Errorf("Err = %v, want nil on a passing check", got.Err)
	}
	if !strings.Contains(got.Detail, strconv.Itoa(port)) {
		t.Errorf("Detail = %q, want it to name the dialled address (port %d)", got.Detail, port)
	}
}

func TestProbeProxyListeningFailsWhenNothingListens(t *testing.T) {
	// Take a port, then release it: nothing is listening on it any more.
	ln, port := listenLoopback(t)
	ln.Close()

	got := ProbeProxyListening(port)

	if got.Name != CheckProxyListening {
		t.Errorf("Name = %q, want %q", got.Name, CheckProxyListening)
	}
	if got.OK {
		t.Errorf("OK = true for a closed port (127.0.0.1:%d); the probe cannot fail, which is worse than no probe", port)
	}
	if got.Err == nil {
		t.Error("Err = nil on a failing check; the failure must carry its cause")
	}
	// A red result that does not say where it looked is not actionable.
	if !strings.Contains(got.Detail, strconv.Itoa(port)) {
		t.Errorf("Detail = %q, want it to name the dialled address (port %d)", got.Detail, port)
	}
}

// The probe dials loopback, never the wildcard address.
func TestProbeProxyListeningDetailIsLoopback(t *testing.T) {
	ln, port := listenLoopback(t)
	defer ln.Close()

	got := ProbeProxyListening(port)

	if !strings.Contains(got.Detail, "127.0.0.1") {
		t.Errorf("Detail = %q, want it to show a 127.0.0.1 address", got.Detail)
	}
	if strings.Contains(got.Detail, "0.0.0.0") {
		t.Errorf("Detail = %q, mentions 0.0.0.0; the probe must dial loopback only", got.Detail)
	}
}
