package bridge

import (
	"strings"
	"testing"
)

// Acceptance test for the DNS resolution check.
//
// Frozen spec: do not edit this file to fit an implementation.
//
// The fixtures need no network and no injection: "localhost" always resolves,
// and the .invalid TLD is reserved by RFC 2606 precisely so that it never does.

func TestProbeHostnameResolvesPassesForANameThatResolves(t *testing.T) {
	got := ProbeHostnameResolves("localhost")

	if got.Name != CheckHostnameResolves {
		t.Errorf("Name = %q, want %q", got.Name, CheckHostnameResolves)
	}
	if !got.OK {
		t.Errorf("OK = false for localhost, which always resolves; err = %v", got.Err)
	}
	if got.Err != nil {
		t.Errorf("Err = %v, want nil on a passing check", got.Err)
	}
	if !strings.Contains(got.Detail, "localhost") {
		t.Errorf("Detail = %q, want it to name what was looked up", got.Detail)
	}
}

func TestProbeHostnameResolvesFailsForANameThatDoesNot(t *testing.T) {
	const nowhere = "mcp-remote-bridge-nothing-here.invalid"

	got := ProbeHostnameResolves(nowhere)

	if got.Name != CheckHostnameResolves {
		t.Errorf("Name = %q, want %q", got.Name, CheckHostnameResolves)
	}
	if got.OK {
		t.Errorf("OK = true for %s, a reserved name that cannot resolve — the check cannot fail, which is worse than no check", nowhere)
	}
	if got.Err == nil {
		t.Error("Err = nil on a failing check; the failure must carry its cause")
	}
	if !strings.Contains(got.Detail, nowhere) {
		t.Errorf("Detail = %q, want it to name what was looked up", got.Detail)
	}
}

// An empty hostname is a caller bug, not a DNS failure, and saying so plainly
// beats reporting "does not resolve" for something never looked up.
func TestProbeHostnameResolvesRejectsAnEmptyHostname(t *testing.T) {
	got := ProbeHostnameResolves("")

	if got.OK {
		t.Error("OK = true for an empty hostname")
	}
	if got.Err == nil {
		t.Fatal("Err = nil for an empty hostname")
	}
}
