package bridge

import (
	"errors"
	"net"
	"strings"
	"testing"
)

// Acceptance test for the DNS resolution check.
//
// Frozen spec: do not edit this file to fit an implementation.
//
// The fixtures need no network and no injection: "localhost" always resolves,
// and the .invalid TLD is reserved by RFC 2606 precisely so that it never does.

func TestProbeHostnameResolvesPassesForANameThatResolves(t *testing.T) {
	got := ProbeHostnameResolves("localhost")

	if got.Name != CheckHostnameResolves {
		t.Errorf("Name = %q, want %q", got.Name, CheckHostnameResolves)
	}
	if !got.OK {
		t.Errorf("OK = false for localhost, which always resolves; err = %v", got.Err)
	}
	if got.Err != nil {
		t.Errorf("Err = %v, want nil on a passing check", got.Err)
	}
	if !strings.Contains(got.Detail, "localhost") {
		t.Errorf("Detail = %q, want it to name what was looked up", got.Detail)
	}
}

func TestProbeHostnameResolvesFailsForANameThatDoesNot(t *testing.T) {
	const nowhere = "mcp-remote-bridge-nothing-here.invalid"

	// Positive control, in the same run and against the same dependency.
	//
	// Without it this test passes just as happily when the RESOLVER is
	// unreachable as when .invalid genuinely NXDOMAINs — the probe would look
	// correct on a machine where nothing resolves at all. Asserting a failure is
	// only as strong as the proof that the dependency was working and said no.
	if control := ProbeHostnameResolves("localhost"); !control.OK {
		t.Skipf("no working resolver in this environment (%v); a negative DNS assertion would prove nothing", control.Err)
	}

	got := ProbeHostnameResolves(nowhere)

	if got.Name != CheckHostnameResolves {
		t.Errorf("Name = %q, want %q", got.Name, CheckHostnameResolves)
	}
	if got.OK {
		t.Errorf("OK = true for %s, a reserved name that cannot resolve — the check cannot fail, which is worse than no check", nowhere)
	}
	if got.Err == nil {
		t.Error("Err = nil on a failing check; the failure must carry its cause")
	}
	if !strings.Contains(got.Detail, nowhere) {
		t.Errorf("Detail = %q, want it to name what was looked up", got.Detail)
	}

	// The specific error, not merely "an error": a timeout, a refused resolver
	// and a genuine NXDOMAIN are three different diagnoses, and only the last
	// one is what this test claims to observe.
	var dnsErr *net.DNSError
	if !errors.As(got.Err, &dnsErr) {
		t.Fatalf("Err = %v, want it to unwrap to a *net.DNSError", got.Err)
	}
	if !dnsErr.IsNotFound {
		t.Errorf("IsNotFound = false (timeout=%v, temporary=%v); the name was not observed to be absent, the lookup merely failed",
			dnsErr.IsTimeout, dnsErr.IsTemporary)
	}
}

// An empty hostname is a caller bug, not a DNS failure, and saying so plainly
// beats reporting "does not resolve" for something never looked up.
func TestProbeHostnameResolvesRejectsAnEmptyHostname(t *testing.T) {
	got := ProbeHostnameResolves("")

	if got.OK {
		t.Error("OK = true for an empty hostname")
	}
	if got.Err == nil {
		t.Fatal("Err = nil for an empty hostname")
	}
}
