package bridge

import (
	"errors"
	"testing"
	"time"
)

// Acceptance test for the settle-and-retry behaviour.
//
// Frozen spec: do not edit this file to fit an implementation.
//
// It uses an injected sleep so the test is instant and deterministic — the
// behaviour under test is "does it retry and stop at the right moment", not
// "does time pass".

// flakyProbe fails the first failures times, then passes.
func flakyProbe(failures int, calls *int) func() Check {
	return func() Check {
		*calls++
		if *calls <= failures {
			return Check{Name: CheckHostnameResponds, Detail: "host", Err: errors.New("not there yet")}
		}
		return Check{Name: CheckHostnameResponds, Detail: "host", OK: true}
	}
}

func TestRetryCheckWaitsForASlowHostname(t *testing.T) {
	calls := 0
	var slept time.Duration

	got := RetryCheck(flakyProbe(5, &calls), time.Minute, 10*time.Second,
		func(d time.Duration) { slept += d })

	if !got.OK {
		t.Fatalf("gave up on a hostname that became reachable after %d attempts: %v", calls, got.Err)
	}
	if calls != 6 {
		t.Errorf("probed %d times, want 6 (five failures then a pass)", calls)
	}
	if slept != 50*time.Second {
		t.Errorf("slept %v between attempts, want 50s (five gaps of 10s)", slept)
	}
}

// A probe that passes immediately must not wait at all — a re-apply on a
// healthy entry stays fast.
func TestRetryCheckDoesNotWaitWhenAlreadyGreen(t *testing.T) {
	calls := 0
	var slept time.Duration

	got := RetryCheck(flakyProbe(0, &calls), time.Minute, 10*time.Second,
		func(d time.Duration) { slept += d })

	if !got.OK {
		t.Fatal("a probe that passes immediately was reported red")
	}
	if calls != 1 {
		t.Errorf("probed %d times, want 1", calls)
	}
	if slept != 0 {
		t.Errorf("slept %v with nothing to wait for", slept)
	}
}

// Giving up must return the LAST real result, not a synthetic timeout: a red
// check has to say where it looked and what failed.
func TestRetryCheckReturnsTheRealFailureWhenItGivesUp(t *testing.T) {
	calls := 0
	probe := func() Check {
		calls++
		return Check{Name: CheckHostnameResponds, Detail: "host.example.com",
			Err: errors.New("connection refused")}
	}

	got := RetryCheck(probe, 30*time.Second, 10*time.Second, func(time.Duration) {})

	if got.OK {
		t.Fatal("reported green after a probe that never passed")
	}
	if got.Err == nil || got.Err.Error() != "connection refused" {
		t.Errorf("Err = %v, want the probe's own error rather than a synthetic timeout", got.Err)
	}
	if got.Detail != "host.example.com" {
		t.Errorf("Detail = %q, want the probe's own detail", got.Detail)
	}
	if got.Name != CheckHostnameResponds {
		t.Errorf("Name = %q, want the probe's own name", got.Name)
	}
	if calls < 2 {
		t.Errorf("probed %d times before giving up on a 30s budget with a 10s interval", calls)
	}
}

// The budget is a bound, not a suggestion.
func TestRetryCheckStopsWithinItsBudget(t *testing.T) {
	calls := 0
	var slept time.Duration
	probe := func() Check {
		calls++
		return Check{Name: CheckHostnameResponds, Err: errors.New("nope")}
	}

	RetryCheck(probe, 25*time.Second, 10*time.Second, func(d time.Duration) { slept += d })

	if slept > 25*time.Second {
		t.Errorf("slept %v, over the 25s budget", slept)
	}
	if calls > 4 {
		t.Errorf("probed %d times on a 25s budget with a 10s interval", calls)
	}
}

// A zero budget still probes once: a wait that never probes reports on nothing.
func TestRetryCheckProbesAtLeastOnce(t *testing.T) {
	calls := 0
	RetryCheck(flakyProbe(1, &calls), 0, 10*time.Second, func(time.Duration) {})

	if calls != 1 {
		t.Errorf("probed %d times with a zero budget, want exactly 1", calls)
	}
}
