package bridge

import "testing"

// Acceptance test for Entry name / subdomain validation.
//
// Frozen spec: do not edit this file to fit an implementation. A name becomes a
// service label, a hostname component AND a log path, so anything outside the
// strict charset is rejected rather than sanitized.
func TestValidateNameRejectsUnsafeInput(t *testing.T) {
	tests := []struct {
		name  string
		input string
		valid bool
	}{
		// Valid.
		{"simple", "standardnotes", true},
		{"with digits", "mcp2", true},
		{"with inner hyphen", "sn-mcp", true},
		{"single character", "a", true},
		{"63 characters is the maximum", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", true},

		// Path traversal — the dangerous family: the name becomes a log path.
		{"parent directory", "..", false},
		{"traversal", "../../etc/passwd", false},
		{"contains slash", "foo/bar", false},
		{"contains backslash", `foo\bar`, false},
		{"leading dot", ".hidden", false},
		{"contains dot", "sn.mcp", false},

		// Charset.
		{"empty", "", false},
		{"uppercase", "StandardNotes", false},
		{"space", "sn mcp", false},
		{"underscore", "sn_mcp", false},
		{"unicode", "café", false},
		{"null byte", "sn\x00mcp", false},
		{"newline", "sn\nmcp", false},

		// Hyphen placement — a DNS label may not start or end with one.
		{"leading hyphen", "-mcp", false},
		{"trailing hyphen", "mcp-", false},

		// Length.
		{"64 characters is too long", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := ValidateName(tt.input)
			if tt.valid && err != nil {
				t.Errorf("ValidateName(%q) = %v, want nil", tt.input, err)
			}
			if !tt.valid && err == nil {
				t.Errorf("ValidateName(%q) = nil, want an error", tt.input)
			}
		})
	}
}

// A subdomain becomes a DNS label and carries the same constraints.
func TestValidateSubdomainRejectsUnsafeInput(t *testing.T) {
	tests := []struct {
		input string
		valid bool
	}{
		{"sn-mcp", true},
		{"freestyle-mcp", true},
		{"", false},
		{"..", false},
		{"foo/bar", false},
		{"Foo", false},
		{"-lead", false},
		{"trail-", false},
		{"has.dot", false},
	}
	for _, tt := range tests {
		err := ValidateSubdomain(tt.input)
		if tt.valid && err != nil {
			t.Errorf("ValidateSubdomain(%q) = %v, want nil", tt.input, err)
		}
		if !tt.valid && err == nil {
			t.Errorf("ValidateSubdomain(%q) = nil, want an error", tt.input)
		}
	}
}
