package launchd

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/lozit/mcp-remote-bridge/internal/bridge"
)

// Acceptance test for launchd plist generation.
//
// Frozen spec: do not edit this file to fit an implementation.
//
// It validates through plutil rather than string comparison: a plist is a
// format, not a byte sequence, and asserting on exact bytes would break on
// harmless formatting while missing a genuinely malformed document.

func testSpec() bridge.ServiceSpec {
	return bridge.ServiceSpec{
		Label:            "com.mcp-remote-bridge.standardnotes",
		Program:          "/usr/local/bin/mcp-remote-bridge",
		Args:             []string{"__launch", "standardnotes", "--config", "/Users/t/.config/mcp-remote-bridge/config.toml", "--port", "8080"},
		StdoutPath:       "/Users/t/Library/Logs/mcp-remote-bridge/standardnotes.log",
		StderrPath:       "/Users/t/Library/Logs/mcp-remote-bridge/standardnotes.log",
		KeepAlive:        bridge.KeepAlivePolicy{OnFailure: true, OnCrash: true},
		ThrottleInterval: 60 * time.Second,
	}
}

// render writes the plist and returns it decoded, having first required plutil
// to accept it as a real property list.
func render(t *testing.T, spec bridge.ServiceSpec) map[string]any {
	t.Helper()
	raw, err := BuildPlist(spec)
	if err != nil {
		t.Fatalf("BuildPlist: %v", err)
	}
	path := filepath.Join(t.TempDir(), "test.plist")
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		t.Fatal(err)
	}
	if runtime.GOOS != "darwin" {
		t.Skip("plist validation needs plutil (macOS)")
	}
	if out, err := exec.Command("plutil", "-lint", path).CombinedOutput(); err != nil {
		t.Fatalf("plutil rejected the generated plist: %v\n%s\n--- generated ---\n%s", err, out, raw)
	}
	out, err := exec.Command("plutil", "-convert", "json", "-o", "-", path).Output()
	if err != nil {
		t.Fatalf("converting the plist: %v", err)
	}
	var decoded map[string]any
	if err := json.Unmarshal(out, &decoded); err != nil {
		t.Fatalf("decoding the converted plist: %v", err)
	}
	return decoded
}

// The plist must carry exactly the specified keys — no more.
//
// This is the load-bearing assertion, and it is not pedantry. The natural way
// to give an MCP its credentials is an EnvironmentVariables section, and the
// plist is world-readable: a future change adding one would put every secret in
// a file any local account can read. An unexpected key fails here.
func TestBuildPlistCarriesExactlyTheExpectedKeys(t *testing.T) {
	got := render(t, testSpec())

	want := []string{
		"Label", "ProgramArguments", "RunAtLoad", "KeepAlive",
		"ThrottleInterval", "StandardOutPath", "StandardErrorPath",
	}
	var keys []string
	for k := range got {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	slices.Sort(want)
	if !slices.Equal(keys, want) {
		t.Errorf("plist keys = %v, want exactly %v", keys, want)
	}
	if _, forbidden := got["EnvironmentVariables"]; forbidden {
		t.Error("the plist declares EnvironmentVariables; the plist is world-readable and must carry no environment")
	}
}

func TestBuildPlistRendersTheProgramAndArguments(t *testing.T) {
	spec := testSpec()
	got := render(t, spec)

	if got["Label"] != spec.Label {
		t.Errorf("Label = %v, want %q", got["Label"], spec.Label)
	}

	rawArgs, ok := got["ProgramArguments"].([]any)
	if !ok {
		t.Fatalf("ProgramArguments is %T, want an array", got["ProgramArguments"])
	}
	var args []string
	for _, a := range rawArgs {
		s, ok := a.(string)
		if !ok {
			t.Fatalf("ProgramArguments contains a %T, want strings only", a)
		}
		args = append(args, s)
	}

	// argv[0] is the program's absolute path, then the spec's arguments.
	want := append([]string{spec.Program}, spec.Args...)
	if !slices.Equal(args, want) {
		t.Errorf("ProgramArguments = %v,\n                  want %v", args, want)
	}
}

// KeepAlive is a dictionary, not a boolean: launchd distinguishes "restart on a
// failing exit" from "restart on a crash", and the working hand-built plists
// this generator must match use the dictionary form.
func TestBuildPlistRendersKeepAliveAsADictionary(t *testing.T) {
	got := render(t, testSpec())

	ka, ok := got["KeepAlive"].(map[string]any)
	if !ok {
		t.Fatalf("KeepAlive is %T, want a dictionary", got["KeepAlive"])
	}
	if ka["SuccessfulExit"] != false {
		t.Errorf("KeepAlive.SuccessfulExit = %v, want false (restart when the program exits non-zero)", ka["SuccessfulExit"])
	}
	if ka["Crashed"] != true {
		t.Errorf("KeepAlive.Crashed = %v, want true", ka["Crashed"])
	}
}

// A policy that asks for nothing must not silently become supervision.
func TestBuildPlistOmitsKeepAliveWhenNothingIsAsked(t *testing.T) {
	spec := testSpec()
	spec.KeepAlive = bridge.KeepAlivePolicy{}
	got := render(t, spec)

	if ka, present := got["KeepAlive"]; present {
		m, ok := ka.(map[string]any)
		if !ok || m["SuccessfulExit"] == false || m["Crashed"] == true {
			t.Errorf("KeepAlive = %v for a zero policy; the service must not be restarted when nothing asked for it", ka)
		}
	}
}

func TestBuildPlistRendersScalarsWithTheRightTypes(t *testing.T) {
	got := render(t, testSpec())

	if got["RunAtLoad"] != true {
		t.Errorf("RunAtLoad = %v (%T), want the boolean true", got["RunAtLoad"], got["RunAtLoad"])
	}
	// Seconds, as an integer — launchd rejects a string here.
	if n, ok := got["ThrottleInterval"].(float64); !ok || int(n) != 60 {
		t.Errorf("ThrottleInterval = %v (%T), want the integer 60", got["ThrottleInterval"], got["ThrottleInterval"])
	}
	if got["StandardOutPath"] != testSpec().StdoutPath {
		t.Errorf("StandardOutPath = %v", got["StandardOutPath"])
	}
	if got["StandardErrorPath"] != testSpec().StderrPath {
		t.Errorf("StandardErrorPath = %v", got["StandardErrorPath"])
	}
}

// XML has five characters that cannot appear raw in text. A path containing one
// would produce a document plutil refuses — or worse, one it misreads.
func TestBuildPlistEscapesXMLMetacharacters(t *testing.T) {
	spec := testSpec()
	spec.Label = `com.test.a&b`
	spec.StdoutPath = `/tmp/a<b>c&d"e'f.log`
	spec.Args = []string{"__launch", `name&<>"'`}

	got := render(t, spec) // plutil -lint inside would already reject a broken document

	if got["Label"] != spec.Label {
		t.Errorf("Label round trip failed: got %q, want %q", got["Label"], spec.Label)
	}
	if got["StandardOutPath"] != spec.StdoutPath {
		t.Errorf("StandardOutPath round trip failed: got %q, want %q", got["StandardOutPath"], spec.StdoutPath)
	}
	args, _ := got["ProgramArguments"].([]any)
	if len(args) != 3 || args[2] != `name&<>"'` {
		t.Errorf("argument round trip failed: %v", args)
	}
}

// The generator must refuse a spec it cannot render honestly, rather than
// emitting a plist that launchd will reject at load time.
func TestBuildPlistRejectsAnIncompleteSpec(t *testing.T) {
	for _, tc := range []struct {
		name   string
		mutate func(*bridge.ServiceSpec)
	}{
		{"no label", func(s *bridge.ServiceSpec) { s.Label = "" }},
		{"no program", func(s *bridge.ServiceSpec) { s.Program = "" }},
		{"relative program path", func(s *bridge.ServiceSpec) { s.Program = "mcp-remote-bridge" }},
		// A throttle below one second truncates to <integer>0</integer>, which
		// disables throttling entirely — the opposite of what it was asked for.
		// The likely cause is a caller that never set the field at all.
		{"zero throttle", func(s *bridge.ServiceSpec) { s.ThrottleInterval = 0 }},
		{"sub-second throttle", func(s *bridge.ServiceSpec) { s.ThrottleInterval = 900 * time.Millisecond }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			spec := testSpec()
			tc.mutate(&spec)
			if _, err := BuildPlist(spec); err == nil {
				t.Errorf("BuildPlist accepted a spec with %s", tc.name)
			}
		})
	}
}

// No secret can reach the plist through ServiceSpec today, and the exact-keys
// test above is what keeps it that way. This one guards the other route in:
// arguments are reproduced verbatim, so a caller cannot be silently "helped"
// by the generator rewriting them.
func TestBuildPlistDoesNotRewriteArguments(t *testing.T) {
	spec := testSpec()
	spec.Args = []string{"__launch", "x", "--config", "/p", "--port", "1"}
	got := render(t, spec)

	rawArgs, ok := got["ProgramArguments"].([]any)
	if !ok || len(rawArgs) != len(spec.Args)+1 {
		t.Fatalf("ProgramArguments = %v, want %d entries (the program plus its arguments)", got["ProgramArguments"], len(spec.Args)+1)
	}
	var joined []string
	for _, a := range rawArgs {
		s, ok := a.(string)
		if !ok {
			t.Fatalf("ProgramArguments contains a %T, want strings only", a)
		}
		joined = append(joined, s)
	}
	if slices.Contains(joined, "-e") || slices.Contains(joined, "--env") {
		t.Errorf("the generator introduced an env flag into the plist: %v", joined)
	}
	if strings.Join(joined[1:], " ") != strings.Join(spec.Args, " ") {
		t.Errorf("arguments were rewritten: got %v, want %v", joined[1:], spec.Args)
	}
}

// A throttle that truncates to zero must be refused, not silently emitted.
//
// This is the failure it prevents: a secret deleted after `apply` makes the
// launcher exit non-zero before starting the proxy; KeepAlive restarts it; with
// ThrottleInterval at 0 that becomes a spin instead of the slow, visible loop
// SPEC-launcher.md asks for. The caller most likely to hit it is one that never
// set the field, so the zero value must not be the dangerous one.
func TestBuildPlistRefusesAThrottleThatTruncatesToZero(t *testing.T) {
	for _, d := range []time.Duration{0, 1 * time.Nanosecond, 999 * time.Millisecond} {
		spec := testSpec()
		spec.ThrottleInterval = d
		if _, err := BuildPlist(spec); err == nil {
			t.Errorf("BuildPlist accepted ThrottleInterval=%v, which renders as 0 and disables throttling", d)
		}
	}
	// One second is the smallest value that survives the conversion.
	spec := testSpec()
	spec.ThrottleInterval = time.Second
	if _, err := BuildPlist(spec); err != nil {
		t.Errorf("BuildPlist rejected ThrottleInterval=1s: %v", err)
	}
}
